.TH "Assets< Resource, Identifier >" 3 "Mon May 21 2018" "DollyEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets< Resource, Identifier >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Assets\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBadd\fP (Identifier id, std::unique_ptr< Resource > res)"
.br
.ti -1c
.RI "bool \fBloadFromFile\fP (Identifier id, const sf::String &filepath)"
.br
.ti -1c
.RI "void \fBremove\fP (Identifier id)"
.br
.ti -1c
.RI "Resource \fBget\fP (Identifier id)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Resource, typename Identifier>
.br
class Assets< Resource, Identifier >"
\fBAssets\fP class for storing and accessing contents in generalized manner 
.PP
\fBBug\fP
.RS 4
loadFromFile not working with sf::Music, use other manager instead 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename Resource , typename Identifier > bool \fBAssets\fP< Resource, Identifier >::add (Identifier id, std::unique_ptr< Resource > res)"
Manually adds an asset to internal container and trying to assign identifier 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP unique identifier 
.br
\fIres\fP resource unique pointer
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIstd::runtime_error\fP if id or pointer is not unique 
.RE
.PP

.SS "template<typename Resource , typename Identifier > bool \fBAssets\fP< Resource, Identifier >::loadFromFile (Identifier id, const sf::String & filepath)"
Loads assets from file (by calling appropriate function) 
.PP
\fBParameters:\fP
.RS 4
\fIid\fP unique identifier 
.br
\fIfilepath\fP file path to resource
.RE
.PP
\fBBug\fP
.RS 4
loadFromFile not working with sf::Music, use other manager instead
.RE
.PP
.PP
\fBReturns:\fP
.RS 4
true if loading is successful and false otherwise 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for DollyEngine from the source code\&.
