.TH "bug" 3 "Mon May 21 2018" "DollyEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bugBug List 
 \- 
.IP "\fBClass \fBAssets< Resource, Identifier >\fP \fP" 1c
loadFromFile not working with sf::Music, use other manager instead  
.IP "\fBMember \fBAssets< Resource, Identifier >::loadFromFile\fP (Identifier id, const sf::String &filepath)\fP" 1c
loadFromFile not working with sf::Music, use other manager instead
.PP

