.TH "Dolly::Map::Tiled::Layout" 3 "Mon May 21 2018" "DollyEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dolly::Map::Tiled::Layout
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "std::vector< int > \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for DollyEngine from the source code\&.
