.TH "Dolly::Map::Tiled::Map" 3 "Mon May 21 2018" "DollyEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dolly::Map::Tiled::Map
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBload\fP (const std::string filename)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBtileheight\fP"
.br
.ti -1c
.RI "int \fBtilewidth\fP"
.br
.ti -1c
.RI "std::vector< \fBLayout\fP > \fBm_layouts\fP"
.br
.ti -1c
.RI "std::vector< \fBObjectGroup\fP > \fBm_groups\fP"
.br
.ti -1c
.RI "std::vector< \fBTileset\fP > \fBm_tilesets\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool Dolly::Map::Tiled::Map::load (const std::string filename)"

.PP
\fBAttention:\fP
.RS 4
DO NOT PASS CHAR VALUES INTO SSCANF WITH X OPTION! 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for DollyEngine from the source code\&.
