.TH "Dolly::Utils::Vector2< Type >" 3 "Mon May 21 2018" "DollyEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dolly::Utils::Vector2< Type >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector2\fP (\fBVector2\fP< Type > o)"
.br
.ti -1c
.RI "\fBVector2\fP (Type x, Type y)"
.br
.ti -1c
.RI "\fBVector2\fP< Type > \fBoperator+\fP (\fBVector2\fP< Type > o)"
.br
.ti -1c
.RI "\fBVector2\fP< Type > \fBoperator\-\fP (\fBVector2\fP< Type > o)"
.br
.ti -1c
.RI "\fBVector2\fP< Type > \fBoperator*\fP (Type val)"
.br
.ti -1c
.RI "\fBVector2\fP< Type > \fBoperator/\fP (Type val)"
.br
.ti -1c
.RI "double \fBmod\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Type \fBx\fP"
.br
.ti -1c
.RI "Type \fBy\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for DollyEngine from the source code\&.
