.TH "Dolly::Configuration::Ini::Ini" 3 "Mon May 21 2018" "DollyEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dolly::Configuration::Ini::Ini
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBload\fP (std::string filename)"
.br
.ti -1c
.RI "bool \fBsave\fP (std::string filename)"
.br
.ti -1c
.RI "std::string \fBgetString\fP (std::string section, std::string key, std::string def='')"
.br
.ti -1c
.RI "std::string \fBsetString\fP (std::string section, std::string key, std::string value)"
.br
.ti -1c
.RI "int \fBgetInt\fP (std::string section, std::string key, int def=0)"
.br
.ti -1c
.RI "int \fBsetInt\fP (std::string section, std::string key, int value)"
.br
.ti -1c
.RI "unsigned \fBgetUInt\fP (std::string section, std::string key, unsigned def=0)"
.br
.ti -1c
.RI "unsigned \fBsetUInt\fP (std::string section, std::string key, unsigned value)"
.br
.ti -1c
.RI "float \fBgetFloat\fP (std::string section, std::string key, float def=0)"
.br
.ti -1c
.RI "float \fBsetFloat\fP (std::string section, std::string key, float value)"
.br
.ti -1c
.RI "bool \fBgetBool\fP (std::string section, std::string key, bool def=false)"
.br
.ti -1c
.RI "bool \fBsetBool\fP (std::string section, std::string key, bool value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for DollyEngine from the source code\&.
