.TH "Dolly::Map::Tiled::Object" 3 "Mon May 21 2018" "DollyEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dolly::Map::Tiled::Object
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBgid\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "std::vector< \fBProperty\fP > \fBpropetries\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for DollyEngine from the source code\&.
