.TH "Tilemap" 3 "Mon May 21 2018" "DollyEngine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tilemap
.SH SYNOPSIS
.br
.PP
.PP
Inherits Drawable, and Transformable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBdraw\fP (sf::RenderTarget &target, sf::RenderStates states) const"
.br
.ti -1c
.RI "void \fBsetTexture\fP (sf::Texture *texture)"
.br
.ti -1c
.RI "void \fBsetData\fP (const int *tiles, sf::Vector2u size)"
.br
.ti -1c
.RI "void \fBsetData\fP (const std::vector< int > tiles, sf::Vector2u size)"
.br
.ti -1c
.RI "void \fBsetData\fP (const std::vector< std::vector< int >> tiles)"
.br
.ti -1c
.RI "void \fBsetTileSize\fP (sf::Vector2u size)"
.br
.ti -1c
.RI "bool \fBareReady\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for DollyEngine from the source code\&.
